on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: lifen.azurecr.io
        username: ${{ secrets.acr_lifen_username }}
        password: ${{ secrets.acr_lifen_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t lifen.azurecr.io/k8sazuredev:${{ github.sha }}
        docker push lifen.azurecr.io/k8sazuredev:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_k8sazuredev_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep lifen-app-dev | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace lifen-app-dev`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: lifen-app-dev
        container-registry-url: lifen.azurecr.io
        container-registry-username: ${{ secrets.acr_lifen_username }}
        container-registry-password: ${{ secrets.acr_lifen_password }}
        secret-name: k8sazuredevdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: lifen-app-dev
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          lifen.azurecr.io/k8sazuredev:${{ github.sha }}
        imagepullsecrets: |
          k8sazuredevdockerauth